instructions = {
	0x00: ['BRK','impl'],
	0x01: ['ORA','X,ind'],
	0x05: ['ORA','zpg'],
	0x06: ['ASL','zpg'],
	0x08: ['PHP','impl'],
	0x09: ['ORA','#'],
	0x0A: ['ASL','A'],
	0x0D: ['ORA','abs'],
	0x0E: ['ASL','abs'],
	0x10: ['BPL','rel'],
	0x11: ['ORA','ind,Y'],
	0x15: ['ORA','zpg,X'],
	0x16: ['ASL','zpg,X'],
	0x18: ['CLC','impl'],
	0x19: ['ORA','abs,Y'],
	0x1D: ['ORA','abs,X'],
	0x1E: ['ASL','abs,X'],
	0x20: ['JSR','abs'],
	0x21: ['AND','X,ind'],
	0x24: ['BIT','zpg'],
	0x25: ['AND','zpg'],
	0x26: ['ROL','zpg'],
	0x28: ['PLP','impl'],
	0x29: ['AND','#'],
	0x2A: ['ROL','A'],
	0x2C: ['BIT','abs'],
	0x2D: ['AND','abs'],
	0x2E: ['ROL','abs'],
	0x30: ['BMI','rel'],
	0x31: ['AND','ind,Y'],
	0x35: ['AND','zpg,X'],
	0x36: ['ROL','zpg,X'],
	0x38: ['SEC','impl'],
	0x39: ['AND','abs,Y'],
	0x3D: ['AND','abs,X'],
	0x3E: ['ROL','abs,X'],
	0x40: ['RTI','impl'],
	0x41: ['EOR','X,ind'],
	0x45: ['EOR','zpg'],
	0x46: ['LSR','zpg'],
	0x48: ['PHA','impl'],
	0x49: ['EOR','#'],
	0x4A: ['LSR','A'],
	0x4C: ['JMP','abs'],
	0x4D: ['EOR','abs'],
	0x4E: ['LSR','abs'],
	0x50: ['BVC','rel'],
	0x51: ['EOR','ind,Y'],
	0x55: ['EOR','zpg,X'],
	0x56: ['LSR','zpg,X'],
	0x58: ['CLI','impl'],
	0x59: ['EOR','abs,Y'],
	0x5D: ['EOR','abs,X'],
	0x5E: ['LSR','abs,X'],
	0x60: ['RTS','impl'],
	0x61: ['ADC','X,ind'],
	0x65: ['ADC','zpg'],
	0x66: ['ROR','zpg'],
	0x68: ['PLA','impl'],
	0x69: ['ADC','#'],
	0x6A: ['ROR','A'],
	0x6C: ['JMP','ind'],
	0x6D: ['ADC','abs'],
	0x6E: ['ROR','abs'],
	0x70: ['BVS','rel'],
	0x71: ['ADC','ind,Y'],
	0x75: ['ADC','zpg,X'],
	0x76: ['ROR','zpg,X'],
	0x78: ['SEI','impl'],
	0x79: ['ADC','abs,Y'],
	0x7D: ['ADC','abs,X'],
	0x7E: ['ROR','abs,X'],
	0x81: ['STA','X,ind'],
	0x84: ['STY','zpg'],
	0x85: ['STA','zpg'],
	0x86: ['STX','zpg'],
	0x88: ['DEY','impl'],
	0x8A: ['TXA','impl'],
	0x8C: ['STY','abs'],
	0x8D: ['STA','abs'],
	0x8E: ['STX','abs'],
	0x90: ['BCC','rel'],
	0x91: ['STA','ind,Y'],
	0x94: ['STY','zpg,X'],
	0x95: ['STA','zpg,X'],
	0x96: ['STX','zpg,Y'],
	0x98: ['TYA','impl'],
	0x99: ['STA','abs,Y'],
	0x9A: ['TXS','impl'],
	0x9D: ['STA','abs,X'],
	0xA0: ['LDY','#'],
	0xA1: ['LDA','X,ind'],
	0xA2: ['LDX','#'],
	0xA4: ['LDY','zpg'],
	0xA5: ['LDA','zpg'],
	0xA6: ['LDX','zpg'],
	0xA8: ['TAY','impl'],
	0xA9: ['LDA','#'],
	0xAA: ['TAX','impl'],
	0xAC: ['LDY','abs'],
	0xAD: ['LDA','abs'],
	0xAE: ['LDX','abs'],
	0xB0: ['BCS','rel'],
	0xB1: ['LDA','ind,Y'],
	0xB4: ['LDY','zpg,X'],
	0xB5: ['LDA','zpg,X'],
	0xB6: ['LDX','zpg,Y'],
	0xB8: ['CLV','impl'],
	0xB9: ['LDA','abs,Y'],
	0xBA: ['TSX','impl'],
	0xBC: ['LDY','abs,X'],
	0xBD: ['LDA','abs,X'],
	0xBE: ['LDX','abs,Y'],
	0xC0: ['CPY','#'],
	0xC1: ['CMP','X,ind'],
	0xC4: ['CPY','zpg'],
	0xC5: ['CMP','zpg'],
	0xC6: ['DEC','zpg'],
	0xC8: ['INY','impl'],
	0xC9: ['CMP','#'],
	0xCA: ['DEX','impl'],
	0xCC: ['CPY','abs'],
	0xCD: ['CMP','abs'],
	0xCE: ['DEC','abs'],
	0xD0: ['BNE','rel'],
	0xD1: ['CMP','ind,Y'],
	0xD5: ['CMP','zpg,X'],
	0xD6: ['DEC','zpg,X'],
	0xD8: ['CLD','impl'],
	0xD9: ['CMP','abs,Y'],
	0xDD: ['CMP','abs,X'],
	0xDE: ['DEC','abs,X'],
	0xE0: ['CPX','#'],
	0xE1: ['SBC','X,ind'],
	0xE4: ['CPX','zpg'],
	0xE5: ['SBC','zpg'],
	0xE6: ['INC','zpg'],
	0xE8: ['INX','impl'],
	0xE9: ['SBC','#'],
	0xEA: ['NOP','impl'],
	0xEC: ['CPX','abs'],
	0xED: ['SBC','abs'],
	0xEE: ['INC','abs'],
	0xF0: ['BEQ','rel'],
	0xF1: ['SBC','ind,Y'],
	0xF5: ['SBC','zpg,X'],
	0xF6: ['INC','zpg,X'],
	0xF8: ['SED','impl'],
	0xF9: ['SBC','abs,Y'],
	0xFD: ['SBC','abs,X'],
	0xFE: ['INC','abs,X'],
	0x02: ['JAM', ''],
	0x03: ['SLO', 'X,ind'],
	0x04: ['NOPs', 'zpg'],
	0x07: ['SLO', 'zpg'],
	0x0B: ['ANC', '#'],
	0x0C: ['NOPs', 'abs'],
	0x0F: ['SLO', 'abs'],
	0x12: ['JAM', ''],
	0x13: ['SLO', 'ind,Y'],
	0x14: ['NOPs', 'zpg,X'],
	0x17: ['SLO', 'zpg,X'],
	0x1A: ['NOPs', 'impl'],
	0x1B: ['SLO', 'abs,Y'],
	0x1C: ['NOPs', 'abs,X'],
	0x1F: ['SLO', 'abs,X'],
	0x22: ['JAM', ''],
	0x23: ['RLA', 'X,ind'],
	0x27: ['RLA', 'zpg'],
	0x2B: ['ANC', '#'],
	0x2F: ['RLA', 'abs'],
	0x32: ['JAM', ''],
	0x33: ['RLA', 'ind,Y'],
	0x34: ['NOPs', 'zpg,X'],
	0x37: ['RLA', 'zpg,X'],
	0x3A: ['NOPs', 'impl'],
	0x3B: ['RLA', 'abs,Y'],
	0x3C: ['NOPs', 'abs,X'],
	0x3F: ['RLA', 'abs,X'],
	0x42: ['JAM', ''],
	0x43: ['SRE', 'X,ind'],
	0x44: ['NOPs', 'zpg'],
	0x47: ['SRE', 'zpg'],
	0x4B: ['ALR', '#'],
	0x4F: ['SRE', 'abs'],
	0x52: ['JAM', ''],
	0x53: ['SRE', 'ind,Y'],
	0x54: ['NOPs', 'zpg,X'],
	0x57: ['SRE', 'zpg,X'],
	0x5A: ['NOPs', 'impl'],
	0x5B: ['SRE', 'abs,Y'],
	0x5C: ['NOPs', 'abs,X'],
	0x5F: ['SRE', 'abs,X'],
	0x62: ['JAM', ''],
	0x63: ['RRA', 'X,ind'],
	0x64: ['NOPs', 'zpg'],
	0x67: ['RRA', 'zpg'],
	0x6B: ['ARR', '#'],
	0x6F: ['RRA', 'abs'],
	0x72: ['JAM', ''],
	0x73: ['RRA', 'ind,Y'],
	0x74: ['NOPs', 'zpg,X'],
	0x77: ['RRA', 'zpg,X'],
	0x7A: ['NOPs', 'impl'],
	0x7B: ['RRA', 'abs,Y'],
	0x7C: ['NOPs', 'abs,X'],
	0x7F: ['RRA', 'abs,X'],
	0x80: ['NOPs', '#'],
	0x82: ['NOPs', '#'],
	0x83: ['SAX', 'X,ind'],
	0x87: ['SAX', 'zpg'],
	0x89: ['NOPs', '#'],
	0x8B: ['ANE', '#'],
	0x8F: ['SAX', 'abs'],
	0x92: ['JAM', ''],
	0x93: ['SHA', 'ind,Y'],
	0x97: ['SAX', 'zpg,Y'],
	0x9B: ['TAS', 'abs,Y'],
	0x9C: ['SHY', 'abs,X'],
	0x9E: ['SHX', 'abs,Y'],
	0x9F: ['SHA', 'abs,Y'],
	0xA3: ['LAX', 'X,ind'],
	0xA7: ['LAX', 'zpg'],
	0xAB: ['LXA', '#'],
	0xAF: ['LAX', 'abs'],
	0xB2: ['JAM', ''],
	0xB3: ['LAX', 'ind,Y'],
	0xB7: ['LAX', 'zpg,Y'],
	0xBB: ['LAS', 'abs,Y'],
	0xBF: ['LAX', 'abs,Y'],
	0xC2: ['NOPs', '#'],
	0xC3: ['DCP', 'X,ind'],
	0xC7: ['DCP', 'zpg'],
	0xCB: ['SBX', '#'],
	0xCF: ['DCP', 'abs'],
	0xD2: ['JAM', ''],
	0xD3: ['DCP', 'ind,Y'],
	0xD4: ['NOPs', 'zpg,X'],
	0xD7: ['DCP', 'zpg,X'],
	0xDA: ['NOPs', 'impl'],
	0xDB: ['DCP', 'abs,Y'],
	0xDC: ['NOPs', 'abs,X'],
	0xDF: ['DCP', 'abs,X'],
	0xE2: ['NOPs', '#'],
	0xE3: ['ISC', 'X,ind'],
	0xE7: ['ISC', 'zpg'],
	0xEB: ['USBC', '#'],
	0xEF: ['ISC', 'abs'],
	0xF2: ['JAM', ''],
	0xF3: ['ISC', 'ind,Y'],
	0xF4: ['NOPs', 'zpg,X'],
	0xF7: ['ISC', 'zpg,X'],
	0xFA: ['NOPs', 'impl'],
	0xFB: ['ISC', 'abs,Y'],
	0xFC: ['NOPs', 'abs,X'],
	0xFF: ['ISC', 'abs,X']
}

map = {  
  "":"none",
  "A":"acc",
  "abs":"abs",
  "abs,X":"absx",
  "abs,Y":"absy",
  "#":"imm",
  "impl":"impl",
  "ind":"ind",
  "ind,X":"indx",
  "ind,Y":"indy",
  "rel":"rel",
  "zpg":"zpg",
  "zpg,X":"zpgx",
  "zpg,Y":"zpgy",
}

def left_pad(a: int, content: str) -> str:
	if a < len(content):
		return content

	loop = a - len(content)
	spaces = ""
	for _ in range(loop):
		spaces = f"{spaces} "

	return f"{spaces}{content}"

nextEndTok = ""
x = 1
for ins in instructions:
	if x == 16:
		nextEndTok = "\n"
		x = 0
	else:
		nextEndTok = ""
	content = f"{map.get(instructions.get(ins)[1])},"
	print(f"{left_pad(6, content)}", end=nextEndTok)
	x += 1;
